---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: wegigo
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: management
    port: 15672
    targetPort: 15672
    # nodePort only limites to: 30000-32767
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: wegigo
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
