html:
  - form: id="form" data-parsley-validate
    fieldset:
      - input: >
               help-label="AutoReply Keyword" v-model="keyword" type=text placeholder="Auto reply keyword" required
               data-parsley-trigger="focusout"
      - textarea: help-label="Reply Message" v-model="reply" rows="3" required data-parsley-trigger="focusout"
      - button: id="btnSave" button-style="primary" text="Save"

javascript:
  - inline: |
      //Wechat Media Platform config
      var vueConfig = new Vue({
          el: '#form',
          data:{
              'keyword': '',
              'reply': '',
          },
      });

      $(document).ready(function(){
        $( "#btnSave" ).on( "click", function() {
          SaveAppConfig(vueConfig);
        });

        LoadAppConfig(vueConfig);
      });




